### ISSUE TITLE
Why was the search feature removed?

### ISSUE THREAD

**Issue by remag9330** [cmlenius/gloomhaven-card-browser#6]
I've noticed the card search feature was removed in 6ecd34d94ec55fcca8303915b5edc649f84021db, was there a reason for this? It was such a great feature to have!

Personally I found it super useful when my group and I would play "remotely" over discord. They could name the card they were playing, and I could bring it up on the stream by searching for it so we could all see the effects.

Is there any chance this feature could make a comeback?

**Comment by cmlenius** [comment]
Sorry for the late reply. I removed it because I was struggling to make the topbar look nice and compact, particularly in the mobile view. I looked at the metrics and the search feature was rarely being used so I ended up removing it.

I probably won't bring it back unless I revamp the UI for some other reason, sorry about that.

**Comment by remag9330** [comment]
Thanks for the reply! And that's understandable. I did take a shot at doing it on my own (hence the PR), so I can keep using that for the time being.

Thanks again for the awesome work!
